### ISSUE TITLE
Edit lyrics and text events

### ISSUE THREAD

**Issue by achimmihca** [markusschwenk/midieditor#106]
Is it possible to edit lyrics and text events?
I have some MIDI files for karaoke (.kar files) that I want to edit.

**Comment by GabrielMiceli** [comment]
All the way at the bottom of the piano roll editor are rows of other MIDI events, one of which is Text. Those are where all text and lyric events are stored.

**Comment by achimmihca** [comment]
True. Don't know why but sometimes the bottom part does not show all events. Then I scroll a bit in the song and new event types show up in the bottom part. Weird
