### ISSUE TITLE
Request: Don't rewind to start when pressing Space.

### ISSUE THREAD

**Issue by YaakovDavis** [markusschwenk/midieditor#3]
I know Ctrl+Space exists, but this isn't consistent with the conventions used in pretty much every other player.

**Comment by GamesOpenSource** [comment]
This is not a player. Any idea how other music creation software handles pressing space to play/pause/continue?

LMMS for one seems to jump to beginning.
FL Studio seems to have the same Space/Ctrl+Space behavior as midieditor
