### ISSUE TITLE
It is difficult to extend the track/channel length when creates new midi files.

### ISSUE THREAD

**Issue by huntercao** [markusschwenk/midieditor#4]
When create new midi-files, the default length is 19.00 s. We cannot find button or command to extend this length. 
Clicking the right arrow button on the bottom track bar cannot extend the length.

**Comment by sergiogsoares** [comment]
You can use the menu: Tools > Set File Duration

**Comment by markusschwenk** [comment]
In the latest version you can also insert measures.
