### ISSUE TITLE
[REQUEST] Discretize red cursor movement

### ISSUE THREAD

**Issue by PROPHESSOR** [markusschwenk/midieditor#42]
![image](https://user-images.githubusercontent.com/19251320/65374153-4eae7180-dc8f-11e9-9956-654a39d6ea6a.png)
Snap it to grid

**Comment by markusschwenk** [comment]
Why? Playback is continuous, not discretized into beats.

**Comment by PROPHESSOR** [comment]
But you can't stop it between two beats
