### ISSUE TITLE
Request: a license for this open source project

### ISSUE THREAD

**Issue by shine5402** [markusschwenk/midieditor#5]
Well, I'm working on a project which needed a MIDI edit feature. I found this amazing project and I want to use a part of the code of this project. But without an license I don't know how should I credit after use the code. Even I don't know if I can use these code.
Therefore, could you place an license under the project dictionary?

**Comment by davidhealey** [comment]
Although there isn't an overall license there is a license header at the top of every source file (at least the ones I've looked at). They all seem to be GNU GPL.

**Comment by shine5402** [comment]
I see.
Thank you for your reply!
